name: Build and Test

on: [push]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - run: pnpm run check:ci

      - run: pnpm test --prefix=./src --if-present

      - run: pnpm run build --prefix=./src --if-present
        env:
          CI: true
