name: Build and Test

on:
  push:
    branches: [main] # Trigger on pushes to main
  pull_request:
    branches: [main] # Trigger on PRs targeting main

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        # It will automatically install tools defined in .mise.toml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.0 # Match .mise.toml

      - name: Setup Node.js (managed by mise)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.mise.toml' # Use version from mise config
          cache: 'pnpm'

      - name: Install dependencies
        # Use mise exec to ensure the correct pnpm version is used
        run: mise exec -- pnpm install --frozen-lockfile

      - name: Run Checks (Lint, Format, Types)
        run: mise exec -- pnpm run check

      - name: Run Tests
        run: mise exec -- pnpm test

      - name: Run Build
        run: mise exec -- pnpm run build
        env:
          CI: true # Some libraries check for CI environment
