name: Build and Test

on: [push]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable
        shell: bash

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --recursive --frozen-lockfile

      - run: pnpm run check:ci

      - run: pnpm --filter ./src --if-present test

      - run: pnpm --filter ./src --if-present run build
        env:
          CI: true
