name: Build and Test

on:
  push:
    branches: [main] # Trigger on pushes to main
  pull_request:
    branches: [main] # Trigger on PRs targeting main

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: npm i -g corepack@latest && corepack enable

      - uses: jdx/mise-action@v2
        with:
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          experimental: true # [default: false] enable experimental features

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Checks (Lint, Format, Types)
        run: pnpm run check:ci

      - name: Run Tests
        run: pnpm test
        env:
          VITEST_VERBOSE: 1

      - name: Run Build
        run: pnpm run build
        env:
          CI: true # Some libraries check for CI environment
