name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "* 0 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Renovate
        uses: renovatebot/github-action@v34.159.2
        with:
          configurationFile: ./.github/renovate-config.js
          token: "${{ secrets.RENOVATE_TOKEN }}"
        env:
          LOG_LEVEL: "debug"
