name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          configurationFile: ./.github/renovate-config.js
          token: "${{ secrets.RENOVATE_TOKEN }}"
        env:
          LOG_LEVEL: "debug"
