name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          configurationFile: ./.github/renovate-config.js
          token: "${{ secrets.RENOVATE_TOKEN }}"
        env:
          LOG_LEVEL: "debug"
